Improved start script (#8)

diff --git a/start b/start
--- a/start
+++ b/start
@@ -1,6 +1,6 @@
 #!/bin/bash
-set -e
 echo "#!/bin/bash" > start.command
+echo "set -exo pipefail" >> start.command
 echo "cd $PWD" >> start.command
 echo "node -r dotenv/config --inspect ./build/app.js" >> start.command
 chmod +x start.command
